Revert "github actions: debugging upload publishing step"
This reverts commit d6d381ad792856e4e0b0c8768f5c22f7e7e97ab5.

diff --git a/.github/workflows/packages.yml b/.github/workflows/packages.yml
--- a/.github/workflows/packages.yml
+++ b/.github/workflows/packages.yml
@@ -235,12 +235,24 @@ jobs:
           # Final part to make changes appear in web root.
           echo "[*] Publishing repository changes..."
 
-          curl \
-            --silent \
-            --user "${{ secrets.APTLY_API_AUTH }}" \
-            --header 'Content-Type: application/json' \
-            --request PUT \
-            --data '{"Signing": {"Passphrase": "${{ secrets.GPG_PASSPHRASE }}"}}' \
-            --write-out "|%{http_code}" \
-             https://packages.termux.org/aptly-api/publish/${REPOSITORY_NAME}/${REPOSITORY_DISTRIBUTION}
+          curl_response=$(
+            curl \
+              --silent \
+              --user "${{ secrets.APTLY_API_AUTH }}" \
+              --header 'Content-Type: application/json' \
+              --request PUT \
+              --data '{"Signing": {"Passphrase": "${{ secrets.GPG_PASSPHRASE }}"}}' \
+              --write-out "|%{http_code}" \
+              https://packages.termux.org/aptly-api/publish/${REPOSITORY_NAME}/${REPOSITORY_DISTRIBUTION}
+          )
+
+          http_status_code=$(echo "$curl_response" | cut -d'|' -f2)
+
+          if [ "$http_status_code" = "200" ]; then
+            echo "[*] Repository updated successfully."
+          else
+            # Note: may return error 500 if gpg signing failed.
+            echo "[*] Server returned $http_status_code."
+            exit 1
+          fi
         fi
