github actions: sync packages.yml with changes made in main repo

diff --git a/.github/workflows/packages.yml b/.github/workflows/packages.yml
--- a/.github/workflows/packages.yml
+++ b/.github/workflows/packages.yml
@@ -1,12 +1,12 @@
 name: Packages
 
 on:
-  pull_request:
-    paths:
-    - 'packages/**'
   push:
     branches:
     - master
+    paths:
+    - 'packages/**'
+  pull_request:
     paths:
     - 'packages/**'
 
@@ -19,17 +19,12 @@ jobs:
     strategy:
       matrix:
         target_arch: [aarch64, arm, i686, x86_64]
+      fail-fast: false
     steps:
     - name: Clone repository
       uses: actions/checkout@v2
       with:
         fetch-depth: 1000
-    - name: Free additional disk space on host
-      run: |
-        sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(cabal-|dotnet-|ghc-|libmono|php)') \
-          liblldb-6.0 libllvm6.0:amd64 mono-runtime-common monodoc-manual ruby
-        sudo apt autoremove -yq
-        sudo rm -rf /usr/local
     - name: Build packages
       run: |
         BASE_COMMIT=$(jq --raw-output .pull_request.base.sha "$GITHUB_EVENT_PATH")
@@ -105,11 +100,20 @@ jobs:
           mv ./deleted_packages.txt.tmp ./deleted_packages.txt
         fi
 
+        if grep -qP '^rust$' ./built_packages.txt ; then
+          echo "Free additional disk space on host"
+          sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(cabal-|dotnet-|ghc-|libmono|php)') \
+            liblldb-6.0 libllvm6.0:amd64 mono-runtime-common monodoc-manual powershell ruby
+          sudo apt autoremove -yq
+          sudo rm -rf /opt/hostedtoolcache /usr/local /usr/share/dotnet /usr/share/swift
+        fi
+
         if [ -f ./built_packages.txt ]; then
           ./scripts/lint-packages.sh $(cat ./built_packages.txt | awk '{print "packages/"$1"/build.sh"}')
           ./start-builder.sh ./build-package.sh -o ./debs -I -a ${{ matrix.target_arch }} $(cat ./built_packages.txt)
         fi
 
+        test -d ./termux-packages/debs && mv ./termux-packages/debs/* ./debs/
         # Put package lists into directory with *.deb files so they will be transferred to
         # upload job.
         test -f ./built_packages.txt && mv ./built_packages.txt ./debs/
@@ -119,11 +123,15 @@ jobs:
         # Files containing certain symbols (e.g. ":") will cause failure in actions/upload-artifact.
         # Archiving *.deb files in a tarball to avoid issues with uploading.
         tar cf artifacts/debs-${{ matrix.target_arch }}-${{ github.sha }}.tar debs
+    - name: Checksums for built *.deb files
+      run: |
+        find debs -type f -name "*.deb" -exec sha256sum "{}" \; | sort -k2
     - name: Store *.deb files
       uses: actions/upload-artifact@v2
       with:
-        name: x11-packages-${{ github.sha }}
+        name: x11-packages-${{ matrix.target_arch }}-${{ github.sha }}
         path: ./artifacts
+
   upload:
     if: github.event_name != 'pull_request'
     needs: build
@@ -134,14 +142,13 @@ jobs:
     - name: Get *.deb files
       uses: actions/download-artifact@v2
       with:
-        name: x11-packages-${{ github.sha }}
         path: ./
     - name: Upload to packages.termux.org
       env:
         REPOSITORY_NAME: termux-x11
         REPOSITORY_DISTRIBUTION: x11
       run: |
-        for archive in *.tar; do
+        for archive in x11-packages-*/*.tar; do
           tar xf "$archive"
         done
 
@@ -207,7 +214,7 @@ jobs:
               --user "${{ secrets.APTLY_API_AUTH }}" \
               --request POST \
               --write-out "|%{http_code}" \
-              https://packages.termux.org/aptly-api/repos/${REPOSITORY_NAME}/file/${REPOSITORY_NAME}-${{ github.sha }}
+              https://packages.termux.org/aptly-api/repos/${REPOSITORY_NAME}/file/${REPOSITORY_NAME}-${{ github.sha }} || true
           )
 
           http_status_code=$(echo "$curl_response" | cut -d'|' -f2)
@@ -220,39 +227,30 @@ jobs:
               echo "$warnings"
               echo
             fi
-
-            # Upload directory is usually deleted automatically once all deb
-            # files were added without issues. Attempting to do this manually
-            # in case it left for some reason (e.g. some debs not added due to
-            # conflicts).
-            aptly_delete_dir
-          else
-            echo "[*] Server returned $http_status_code. Not publishing repository!"
-            aptly_delete_dir
-            exit 1
           fi
+          # Usually temporary directory is deleted automatically, but in certain cases it is left.
+          aptly_delete_dir
 
           # Final part to make changes appear in web root.
           echo "[*] Publishing repository changes..."
+          set +e
+          curl \
+            --silent \
+            --user "${{ secrets.APTLY_API_AUTH }}" \
+            --header 'Content-Type: application/json' \
+            --request PUT \
+            --data '{"Signing": {"Passphrase": "${{ secrets.GPG_PASSPHRASE }}"}}' \
+            https://packages.termux.org/aptly-api/publish/${REPOSITORY_NAME}/${REPOSITORY_DISTRIBUTION}
+          exit_code=$?
+          echo
 
-          curl_response=$(
-            curl \
-              --silent \
-              --user "${{ secrets.APTLY_API_AUTH }}" \
-              --header 'Content-Type: application/json' \
-              --request PUT \
-              --data '{"Signing": {"Passphrase": "${{ secrets.GPG_PASSPHRASE }}"}}' \
-              --write-out "|%{http_code}" \
-              https://packages.termux.org/aptly-api/publish/${REPOSITORY_NAME}/${REPOSITORY_DISTRIBUTION}
-          )
-
-          http_status_code=$(echo "$curl_response" | cut -d'|' -f2)
-
-          if [ "$http_status_code" = "200" ]; then
+          if [ "$exit_code" = 0 ]; then
             echo "[*] Repository updated successfully."
+          elif [ "$exit_code" = 52 ]; then
+            echo "[!] Repository update takes more time than expected, server returned empty response."
+            echo "[!] This is expected if large amount of data has been submitted."
           else
-            # Note: may return error 500 if gpg signing failed.
-            echo "[*] Server returned $http_status_code."
-            exit 1
+            echo "[!] curl exited with error code $exit_status."
+            exit "$exit_code"
           fi
         fi
